---

- group: pps
  name: width
  type: int
  max: 1000000
  min: 0

- group: surveyed_position
  name: surveyed_lat
  type: float
  max: 90.0
  min: -90.0

- group: surveyed_position
  name: surveyed_lon
  type: float
  max: 180.0
  min: -180.0

- group: surveyed_position
  name: surveyed_alt
  type: float
  max: 20000.0
  min: -100.0

- group: sbp
  name: obs_msg_max_size
  type: int
  max: 255
  min: 1

- group: simulator
  name: base_ecef_x
  type: float
  max: 10000000
  min: -10000000

- group: simulator
  name: base_ecef_y
  type: float
  max: 10000000
  min: -10000000

- group: simulator
  name: base_ecef_z
  type: float
  max: 10000000
  min: -10000000

- group: simulator
  name: speed
  type: float
  max: 1000
  min: 0

- group: simulator
  name: radius
  type: float
  max: 42000
  min: 0

- group: simulator
  name: pos_sigma
  type: float
  max: 90.0
  min: 0

- group: simulator
  name: speed_sigma
  type: float
  max: 90.0
  min: 0

- group: simulator
  name: cn0_sigma
  type: float
  max: 90.0
  min: 0

- group: simulator
  name: pseudorange_sigma
  type: float
  max: 90.0
  min: 0

- group: simulator
  name: phase_sigma
  type: float
  max: 90.0
  min: 0

- group: simulator
  name: num_sats
  type: int
  max: 20
  min: 0

- group: simulator
  name: mode_mask
  type: int
  max: 15
  min: 0

- group: solution
  name: soln_freq
  type: int
  max: 20
  min: 0

- group: solution
  name: output_every_n_obs
  type: int
  max: 20
  min: 1

- group: solution
  name: known_baseline_n
  type: float
  max: 10000
  min: -10000

- group: solution
  name: known_baseline_e
  type: float
  max: 10000
  min: -10000

- group: solution
  name: known_baseline_d
  type: float
  max: 10000
  min: -10000

- group: solution
  name: elevation_mask
  type: float
  max: 90.0
  min: 0.0

- group: system_monitor
  name: heartbeat_period_milliseconds
  type: int
  max: 10000
  min: 1000

- group: uart_ftdi
  name: sbp_message_mask
  type: int
  max: 65535
  min: 0

- group: uart_ftdi
  name: baudrate
  type: int
  max: 1000000
  min: 0

- group: uart_uarta
  name: sbp_message_mask
  type: int
  max: 65535
  min: 0

- group: uart_uarta
  name: baudrate
  type: int
  max: 1000000
  min: 0

- group: uart_uartb
  name: sbp_message_mask
  type: int
  max: 65535
  min: 0

- group: uart_uartb
  name: baudrate
  type: int
  max: 1000000
  min: 0

- group: nmea
  name: gpgsv_msg_rate
  type: int
  max: 20
  min: 0

- group: nmea
  name: gprmc_msg_rate
  type: int
  max: 20
  min: 0

- group: nmea
  name: gpvtg_msg_rate
  type: int
  max: 20
  min: 0

- group: nmea
  name: gpgll_msg_rate
  type: int
  max: 20
  min: 0

- group: surveyed_position
  name: broadcast
  type: bool

- group: simulator
  name: enabled
  type: bool

- group: system_monitor
  name: watchdog
  type: bool

- group: uart_uarta
  name: configure_telemetry_radio_on_boot
  type: bool

- group: uart_uartb
  name: configure_telemetry_radio_on_boot
  type: bool

- group: uart_ftdi
  name: mode
  type: enum
  enum: ['SBP','NMEA']

- group: uart_uarta
  name: mode
  type: enum
  enum: ['SBP','NMEA']

- group: uart_uarta
  name: configure_telemetry_radio_on_boot
  type: enum
  enum: ['False','True']

- group: uart_uartb
  name: mode
  type: enum
  enum: ['SBP','NMEA']

- group: uart_uartb
  name: configure_telemetry_radio_on_boot
  type: enum
  enum: ['False','True']

- group: frontend
  name: antenna_selection
  type: enum
  enum: ['Auto','Patch','External','External (no bias)']

- group: ext_events
  name: edge_trigger
  type: enum
  enum: ['None','Rising','Falling','Both']

- group: track
  name: alias_detect
  type: enum
  enum: ['False','True']

- group: solution
  name: dgnss_solution_mode
  type: enum
  enum: ['Low Latency','Time Matched']

- group: solution
  name: dgnss_filter
  type: enum
  enum: ['Float','Fixed']

- group: solution
  name: disable_raim
  type: enum
  enum: ['False','True']

- group: solution
  name: send_heading
  type: enum
  enum: ['False','True']

- group: system_monitor
  name: watchdog
  type: enum
  enum: ['False','True']

- group: surveyed_position
  name: broadcast
  type: enum
  enum: ['False','True']

- group: simulator
  name: enabled
  type: enum
  enum: ['False','True']
